### ISSUE TITLE
URL query style location.hash parameters

### ISSUE THREAD

**Issue by Zapotek** [yahoo/webseclab#9]
I think it'd be a good idea to convert this:

```
http://127.0.0.2:8080/xss/dom/yuinode_hash?#in=xyz
```

to:

```
http://127.0.0.2:8080/xss/dom/yuinode_hash#/?in=xyz
```

It's a small change but the current convention seems to be to emulate the usual URL style in the hash.

Example:

```
http://testhtml5.vulnweb.com/#/redir?url=http://www.thoughtcrime.org/blog/gpg-and-me/
```

Also, scanners usually play ball with the 2nd style automatically, otherwise folks trying them against webseclab will need to provide further configuration.

What do you think?

**Comment by dmitris** [comment]
Good idea - how about if we have both cases side-by-side?

**Comment by Zapotek** [comment]
Sounds good to me.

**Comment by dmitris** [comment]
Let me know if https://github.com/yahoo/webseclab/pull/11 covers what you asked for :smile:

**Comment by dmitris** [comment]
merged https://github.com/yahoo/webseclab/pull/11
